name: Modern App Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: ./traccar-web/package-lock.json
    - name: ci
      run: npm ci
      working-directory: ./traccar-web
    - name: lint
      run: npm run lint
      working-directory: ./traccar-web